#TODO:
# - add volumes
# - add adminer initial config
# - add backup script
# - add restore script
# - add logs
# - add metrics
# - add alerts
# - add monitoring
# - add security
# - add backup

version: '3.1'
name: mariadb-container
services:

  mariadb:
    image: mariadb:10.6.15
    restart: always
    #volumes:
      #- db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: passw0rd
      MARIADB_DATABASE: admindb 
      MARIADB_ROOT_PASSWORD: admin
    networks:
      - db-network


  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
     - db-network
      

networks:
  db-network:
    driver: bridge
    external: true