version: '3.4'

name: seq

services:
  
  mail:  
    #info: https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml 
    image: rnwood/smtp4dev:v3
    container_name: mail-mock-server
    ports:
      - "6080:80"
      - "25:25"
      - "143:143"

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      ACCEPT_EULA=Y
      #SEQ_FIRSTRUN_ADMINPASSWORDHASH="$PH"
    ports:
      - "6080:80"
      - "25:25"
      - "143:143"   