version: '3.8'
name: sql-server

services:
  db:
    #info: https://hub.docker.com/_/microsoft-mssql-server       
#      image: mcr.microsoft.com/mssql/server:2019-latest
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=qwerty$123
    ports:
      - 1435:1433
    volumes:
      - ./data:/var/opt/mssql/data