#TODO:
# - add volumes
# - add logs
# - add metrics
# - add alerts
# - add monitoring
# - add security

version: '3.1'
name: snipe-it
services:
  snipe-it:
    image: snipe/snipe-it:latest
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    networks:
      - db-network


  mail-it:
    #info: https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml 
    image: rnwood/smtp4dev:v3
    container_name: mail-mock-server
    ports:
      - "6080:80"
      - "25:25"
      - "143:143"      